import { neon } from "@neondatabase/serverless";
import bcrypt from "bcryptjs";

const url = process.env.DATABASE_URL;
if (!url) {
  console.error("[seed] Missing DATABASE_URL");
  process.exit(1);
}

const sql = neon(url);

// ---------------------------------------------------------------
// ADMIN
// ---------------------------------------------------------------
const adminUsername = process.env.ADMIN_USERNAME || "admin";
const adminPassword = process.env.ADMIN_PASSWORD || "admin123";
const hash = bcrypt.hashSync(adminPassword, 10);

await sql`
  INSERT INTO admins (username, password_hash)
  VALUES (${adminUsername}, ${hash})
  ON CONFLICT (username) DO UPDATE SET password_hash = EXCLUDED.password_hash
`;
console.log(`[seed] Admin ready: ${adminUsername}`);

// ---------------------------------------------------------------
// SEGMENTS (4 phân khúc giá)
// ---------------------------------------------------------------
const B = 1_000_000_000;

const segments = [
  {
    slug: "duoi-3-ty",
    name: "Phân khúc dưới 3 tỷ",
    short_name: "Dưới 3 tỷ",
    tagline: "Khởi đầu an cư",
    description:
      "Những căn hộ, nhà phố compact phù hợp gia đình trẻ, người mua ở thực lần đầu. Vị trí thuận tiện, tiện ích đầy đủ, pháp lý rõ ràng.",
    price_min: null,
    price_max: 3 * B - 1,
    image_url:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80",
    accent: "emerald",
    sort_order: 1,
  },
  {
    slug: "tu-3-den-6-ty",
    name: "Phân khúc 3 – 6 tỷ",
    short_name: "3 – 6 tỷ",
    tagline: "Nâng tầm chuẩn sống",
    description:
      "Căn hộ cao cấp, nhà phố mặt tiền, townhouse trong khu đô thị. Phù hợp gia đình muốn nâng cấp không gian sống và đầu tư dài hạn.",
    price_min: 3 * B,
    price_max: 6 * B - 1,
    image_url:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
    accent: "sapphire",
    sort_order: 2,
  },
  {
    slug: "tu-6-den-10-ty",
    name: "Phân khúc 6 – 10 tỷ",
    short_name: "6 – 10 tỷ",
    tagline: "Không gian đẳng cấp",
    description:
      "Penthouse, duplex, villa biên hoà thiên nhiên và biệt thự compound. Tối ưu cho giới thượng lưu yêu cầu không gian riêng tư, sang trọng.",
    price_min: 6 * B,
    price_max: 10 * B - 1,
    image_url:
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1600&q=80",
    accent: "gold",
    sort_order: 3,
  },
  {
    slug: "tren-10-ty",
    name: "Phân khúc trên 10 tỷ",
    short_name: "Trên 10 tỷ",
    tagline: "Di sản để lại",
    description:
      "Bộ sưu tập giới hạn: biệt thự triệu đô, penthouse view sông, villa compound ven sông Sài Gòn. Một định nghĩa về di sản.",
    price_min: 10 * B,
    price_max: null,
    image_url:
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80",
    accent: "ruby",
    sort_order: 4,
  },
];

for (const s of segments) {
  await sql`
    INSERT INTO segments (slug, name, short_name, tagline, description, price_min, price_max, image_url, accent, sort_order)
    VALUES (${s.slug}, ${s.name}, ${s.short_name}, ${s.tagline}, ${s.description},
            ${s.price_min}, ${s.price_max}, ${s.image_url}, ${s.accent}, ${s.sort_order})
    ON CONFLICT (slug) DO UPDATE SET
      name = EXCLUDED.name,
      short_name = EXCLUDED.short_name,
      tagline = EXCLUDED.tagline,
      description = EXCLUDED.description,
      price_min = EXCLUDED.price_min,
      price_max = EXCLUDED.price_max,
      image_url = EXCLUDED.image_url,
      accent = EXCLUDED.accent,
      sort_order = EXCLUDED.sort_order
  `;
}
console.log(`[seed] Segments ready: ${segments.length}`);

const rows = await sql`SELECT id, slug FROM segments`;
const sId = Object.fromEntries(rows.map((r) => [r.slug, r.id]));

// ---------------------------------------------------------------
// PROPERTIES (23 mẫu)
// ---------------------------------------------------------------
const img = (q) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=1600&q=80`;

const properties = [
  // ================== DƯỚI 3 TỶ ==================
  {
    slug: "can-ho-2pn-vinhomes-grand-park-q9",
    title: "Căn hộ 2PN Vinhomes Grand Park, Quận 9",
    subtitle: "Tầng cao, view nội khu, full nội thất",
    segment: "duoi-3-ty",
    property_type: "can-ho",
    price: 2_750_000_000,
    area: 60.5,
    bedrooms: 2,
    bathrooms: 2,
    direction: "Đông Nam",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Nguyên Xiển",
    district: "Quận 9",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1522708323590-d24dbb6b0267"),
    gallery: [
      img("photo-1505693314120-0d443867891c"),
      img("photo-1505692794403-34cb4942c819"),
      img("photo-1616486338812-3dadae4b4ace"),
    ],
    amenities: ["Hồ bơi", "Gym", "Công viên", "School bus", "Shuttle Metro"],
    highlights: [
      "View nội khu, hướng Đông Nam đón nắng sáng",
      "Cách trung tâm Q.1 khoảng 25 phút di chuyển",
      "Mật độ xây dựng thấp, mật độ xanh 72%",
    ],
    is_featured: true,
  },
  {
    slug: "nha-pho-3-tang-binh-tan-hem-xe-hoi",
    title: "Nhà phố 3 tầng Bình Tân, hẻm xe hơi",
    subtitle: "4x15m, 3PN, pháp lý hoàn chỉnh",
    segment: "duoi-3-ty",
    property_type: "nha-pho",
    price: 2_950_000_000,
    area: 60.0,
    bedrooms: 3,
    bathrooms: 3,
    floors: 3,
    direction: "Nam",
    legal: "Sổ hồng riêng",
    furniture: "Cơ bản",
    address: "Đường số 7",
    district: "Quận Bình Tân",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1572120360610-d971b9d7767c"),
    gallery: [img("photo-1502005229762-cf1b2da7c5d6"), img("photo-1484154218962-a197022b5858")],
    amenities: ["Gần chợ", "Gần trường", "Gần Aeon Mall"],
    highlights: ["Hẻm xe hơi 5m", "Khu dân cư an ninh", "Nội thất gỗ tự nhiên"],
  },
  {
    slug: "studio-38m2-the-origami-q9",
    title: "Studio 38m² The Origami, Quận 9",
    subtitle: "Đầu tư cho thuê, giá tốt",
    segment: "duoi-3-ty",
    property_type: "can-ho",
    price: 1_890_000_000,
    area: 38.0,
    bedrooms: 1,
    bathrooms: 1,
    direction: "Đông",
    legal: "Hợp đồng mua bán",
    furniture: "Full nội thất",
    address: "Nguyên Xiển",
    district: "Quận 9",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1502672023488-70e25813eb80"),
    gallery: [img("photo-1501183638710-841dd1904471")],
    amenities: ["Hồ bơi Origami", "Gym", "Công viên trung tâm"],
    highlights: ["Dòng tiền cho thuê ~12tr/tháng", "Full nội thất cao cấp"],
  },
  {
    slug: "can-ho-2pn-mizuki-park-binh-chanh",
    title: "Căn hộ 2PN Mizuki Park, Bình Chánh",
    subtitle: "View hồ sinh thái, an cư chuẩn Nhật",
    segment: "duoi-3-ty",
    property_type: "can-ho",
    price: 2_480_000_000,
    area: 72.0,
    bedrooms: 2,
    bathrooms: 2,
    direction: "Tây Nam",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Nguyễn Văn Linh",
    district: "Bình Chánh",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600607687939-ce8a6c25118c"),
    gallery: [img("photo-1600607687644-c7171b42498f"), img("photo-1600566753376-12c8ab7fb75b")],
    amenities: ["Hồ sinh thái", "Vườn Nhật", "Minimart", "Sân tennis"],
    highlights: ["View hồ sinh thái 3.6ha", "Nội thất Nhật Bản"],
  },
  {
    slug: "can-ho-1pn-akari-city-binh-tan",
    title: "Căn hộ 1PN Akari City, Bình Tân",
    subtitle: "Chuẩn sống Nhật, giao thông thuận tiện",
    segment: "duoi-3-ty",
    property_type: "can-ho",
    price: 1_650_000_000,
    area: 55.0,
    bedrooms: 1,
    bathrooms: 1,
    direction: "Đông",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Võ Văn Kiệt",
    district: "Quận Bình Tân",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1560448204-e02f11c3d0e2"),
    gallery: [img("photo-1522708323590-d24dbb6b0267")],
    amenities: ["Trường Nhật Bản", "Hồ bơi", "Công viên 3ha"],
    highlights: ["Dễ dàng cho thuê lại", "Chuẩn sống Nhật Bản"],
  },

  // ================== 3 – 6 TỶ ==================
  {
    slug: "can-ho-3pn-masteri-an-phu-q2",
    title: "Căn hộ 3PN Masteri An Phú, Quận 2",
    subtitle: "View sông Sài Gòn, bàn giao cao cấp",
    segment: "tu-3-den-6-ty",
    property_type: "can-ho",
    price: 5_800_000_000,
    area: 96.0,
    bedrooms: 3,
    bathrooms: 2,
    direction: "Đông Nam",
    legal: "Sổ hồng",
    furniture: "Full nội thất cao cấp",
    address: "Xa lộ Hà Nội",
    district: "Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600585154340-be6161a56a0c"),
    gallery: [
      img("photo-1600607687939-ce8a6c25118c"),
      img("photo-1600566753190-17f0baa2a6c3"),
      img("photo-1600566752355-35792bedcfea"),
    ],
    amenities: ["Infinity pool", "Sky garden", "Cigar lounge", "Gym 1000m²"],
    highlights: [
      "View sông Sài Gòn trực diện",
      "Bàn giao nội thất cao cấp từ Châu Âu",
      "Cách Metro Bến Thành 15 phút",
    ],
    is_featured: true,
    is_hero: true,
  },
  {
    slug: "nha-pho-van-phuc-city-thu-duc",
    title: "Nhà phố Vạn Phúc City, Thủ Đức",
    subtitle: "5x20m, 4PN, sổ hồng sẵn",
    segment: "tu-3-den-6-ty",
    property_type: "nha-pho",
    price: 5_300_000_000,
    area: 100.0,
    bedrooms: 4,
    bathrooms: 4,
    floors: 4,
    direction: "Đông Bắc",
    legal: "Sổ hồng",
    furniture: "Cơ bản",
    address: "Vạn Phúc City",
    district: "TP. Thủ Đức",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1572120360610-d971b9d7767c"),
    gallery: [img("photo-1564501049412-61c2a3083791"), img("photo-1600585154526-990dced4db0d")],
    amenities: ["Công viên bờ sông", "Trường Quốc tế", "Clubhouse"],
    highlights: ["Khu compound bờ sông", "Đường 20m", "An ninh 24/7"],
    is_featured: true,
  },
  {
    slug: "townhouse-cityland-go-vap",
    title: "Townhouse Cityland, Gò Vấp",
    subtitle: "Kinh doanh mặt tiền, dòng tiền ổn định",
    segment: "tu-3-den-6-ty",
    property_type: "shophouse",
    price: 4_900_000_000,
    area: 84.0,
    bedrooms: 3,
    bathrooms: 4,
    floors: 4,
    direction: "Tây Nam",
    legal: "Sổ hồng",
    furniture: "Trống",
    address: "Phan Văn Trị",
    district: "Quận Gò Vấp",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1545324418-cc1a3fa10c00"),
    gallery: [img("photo-1564013799919-ab600027ffc6")],
    amenities: ["Mặt tiền 24m", "Gần trung tâm hành chính"],
    highlights: ["Đang cho thuê 60tr/tháng", "Khu compound có ba-ri-e"],
  },
  {
    slug: "can-ho-3pn-d-edge-thao-dien",
    title: "Căn hộ 3PN D'Edge Thảo Điền",
    subtitle: "View sông, bàn giao full nội thất châu Âu",
    segment: "tu-3-den-6-ty",
    property_type: "can-ho",
    price: 5_950_000_000,
    area: 112.0,
    bedrooms: 3,
    bathrooms: 3,
    direction: "Đông",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Quốc Hương",
    district: "Thảo Điền, Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600566753190-17f0baa2a6c3"),
    gallery: [img("photo-1600566753086-00f18fe6ba68"), img("photo-1600566753376-12c8ab7fb75b")],
    amenities: ["Infinity pool view sông", "Sky lounge", "Kids club"],
    highlights: ["Đẳng cấp quốc tế", "Tiện ích 5 sao"],
  },
  {
    slug: "villa-mini-pham-van-dong",
    title: "Villa mini Phạm Văn Đồng, Thủ Đức",
    subtitle: "Sân vườn 30m², hồ cá Koi",
    segment: "tu-3-den-6-ty",
    property_type: "villa",
    price: 5_700_000_000,
    area: 160.0,
    bedrooms: 4,
    bathrooms: 4,
    floors: 3,
    direction: "Đông Nam",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Phạm Văn Đồng",
    district: "TP. Thủ Đức",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600566753051-6057c5c34e6a"),
    gallery: [img("photo-1600607687939-ce8a6c25118c")],
    amenities: ["Hồ cá Koi", "Sân vườn", "Garage 2 xe"],
    highlights: ["Thiết kế resort", "Hệ thống smart home"],
  },
  {
    slug: "can-ho-dual-key-metropole-q2",
    title: "Căn hộ Dual Key Metropole, Quận 2",
    subtitle: "Thiết kế 1+2 phòng ngủ độc lập",
    segment: "tu-3-den-6-ty",
    property_type: "can-ho",
    price: 4_500_000_000,
    area: 88.0,
    bedrooms: 3,
    bathrooms: 3,
    direction: "Tây",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Trần Não",
    district: "Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600566753376-12c8ab7fb75b"),
    gallery: [img("photo-1600566752355-35792bedcfea")],
    amenities: ["Infinity pool", "Business center", "Spa"],
    highlights: ["Dual key hiếm có", "Vừa ở vừa cho thuê"],
  },

  // ================== 6 – 10 TỶ ==================
  {
    slug: "penthouse-duplex-feliz-en-vista-q2",
    title: "Penthouse Duplex Feliz en Vista, Quận 2",
    subtitle: "285m² thông tầng, view sông Sài Gòn",
    segment: "tu-6-den-10-ty",
    property_type: "penthouse",
    price: 9_800_000_000,
    area: 285.0,
    bedrooms: 4,
    bathrooms: 5,
    floors: 2,
    direction: "Đông Nam",
    legal: "Sổ hồng",
    furniture: "Full nội thất thiết kế riêng",
    address: "Phan Văn Đáng",
    district: "Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1613977257363-707ba9348227"),
    gallery: [
      img("photo-1600566753190-17f0baa2a6c3"),
      img("photo-1600585154340-be6161a56a0c"),
      img("photo-1600607687939-ce8a6c25118c"),
    ],
    amenities: ["Sky pool riêng", "Cigar lounge", "Private lift", "Bếp đảo"],
    highlights: [
      "285m² thông tầng, trần cao 6m",
      "Thang máy riêng lên tận căn",
      "View trọn sông Sài Gòn & Landmark 81",
    ],
    is_featured: true,
    is_hero: true,
  },
  {
    slug: "biet-thu-pho-lakeview-city-q2",
    title: "Biệt thự phố Lakeview City, Quận 2",
    subtitle: "7x20m, 5PN, view hồ điều hoà",
    segment: "tu-6-den-10-ty",
    property_type: "biet-thu",
    price: 9_200_000_000,
    area: 140.0,
    bedrooms: 5,
    bathrooms: 5,
    floors: 4,
    direction: "Tây Nam",
    legal: "Sổ hồng",
    furniture: "Cơ bản",
    address: "Lakeview City",
    district: "Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1568605114967-8130f3a36994"),
    gallery: [img("photo-1613977257592-4871e5fcd7c4"), img("photo-1616596883611-50f6d1ba4dfe")],
    amenities: ["Hồ điều hoà", "Clubhouse", "Cổng compound"],
    highlights: ["View hồ điều hoà", "Mặt tiền đường 16m"],
    is_featured: true,
  },
  {
    slug: "penthouse-diamond-island-q2",
    title: "Penthouse Diamond Island, Quận 2",
    subtitle: "220m², rooftop riêng",
    segment: "tu-6-den-10-ty",
    property_type: "penthouse",
    price: 8_500_000_000,
    area: 220.0,
    bedrooms: 4,
    bathrooms: 4,
    direction: "Đông",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Đảo Kim Cương",
    district: "Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600566753086-00f18fe6ba68"),
    gallery: [img("photo-1600566753051-6057c5c34e6a")],
    amenities: ["Bán đảo", "Rooftop", "Clubhouse bãi biển nhân tạo"],
    highlights: ["Rooftop riêng 60m²", "View 360 độ sông"],
  },
  {
    slug: "biet-thu-don-lap-vinhomes-central-park",
    title: "Biệt thự đơn lập Vinhomes Central Park",
    subtitle: "Bên sông, 300m² sàn, hồ bơi riêng",
    segment: "tu-6-den-10-ty",
    property_type: "biet-thu",
    price: 9_950_000_000,
    area: 260.0,
    bedrooms: 5,
    bathrooms: 6,
    floors: 3,
    direction: "Đông Bắc",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Nguyễn Hữu Cảnh",
    district: "Quận Bình Thạnh",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1613490493576-7fde63acd811"),
    gallery: [img("photo-1613977257363-707ba9348227"), img("photo-1600566753086-00f18fe6ba68")],
    amenities: ["Hồ bơi riêng", "Công viên 14ha", "Bến du thuyền"],
    highlights: ["Bước ra bờ sông", "Compound an ninh tuyệt đối"],
  },
  {
    slug: "shophouse-sun-avenue-xa-lo-ha-noi",
    title: "Shophouse Sun Avenue, Xa lộ Hà Nội",
    subtitle: "Mặt tiền 8m, đang vận hành nhà hàng",
    segment: "tu-6-den-10-ty",
    property_type: "shophouse",
    price: 7_800_000_000,
    area: 180.0,
    bedrooms: 2,
    bathrooms: 4,
    floors: 2,
    direction: "Đông Nam",
    legal: "Sổ hồng",
    furniture: "Full thiết bị nhà hàng",
    address: "Mai Chí Thọ",
    district: "Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1545324418-cc1a3fa10c00"),
    gallery: [img("photo-1564013799919-ab600027ffc6")],
    amenities: ["Mặt tiền Mai Chí Thọ", "Lượng khách lớn"],
    highlights: ["Doanh thu ổn định 1.5 tỷ/tháng", "Hợp đồng thuê 10 năm"],
  },

  // ================== TRÊN 10 TỶ ==================
  {
    slug: "biet-thu-compound-thao-dien-ven-song",
    title: "Biệt thự compound Thảo Điền ven sông",
    subtitle: "Resort riêng, 500m² đất, hồ bơi & bến thuyền",
    segment: "tren-10-ty",
    property_type: "biet-thu",
    price: 35_000_000_000,
    area: 500.0,
    bedrooms: 6,
    bathrooms: 7,
    floors: 3,
    direction: "Đông Nam",
    legal: "Sổ hồng",
    furniture: "Nội thất custom thiết kế riêng",
    address: "Nguyễn Văn Hưởng",
    district: "Thảo Điền, Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1613490493576-7fde63acd811"),
    gallery: [
      img("photo-1613977257363-707ba9348227"),
      img("photo-1600607687939-ce8a6c25118c"),
      img("photo-1600566753376-12c8ab7fb75b"),
    ],
    amenities: ["Bến du thuyền riêng", "Hồ bơi vô cực", "Phòng xông hơi", "Rạp phim"],
    highlights: [
      "500m² đất, 3 mặt view sông",
      "Bến thuyền & hồ bơi tràn bờ hướng sông",
      "Compound an ninh với 12 biệt thự cùng tiêu chuẩn",
    ],
    is_featured: true,
    is_hero: true,
  },
  {
    slug: "penthouse-landmark-81-binh-thanh",
    title: "Penthouse Landmark 81, Bình Thạnh",
    subtitle: "Tầng 78, 360° view toàn Sài Gòn",
    segment: "tren-10-ty",
    property_type: "penthouse",
    price: 58_000_000_000,
    area: 380.0,
    bedrooms: 4,
    bathrooms: 5,
    direction: "Đông",
    legal: "Sổ hồng",
    furniture: "Full nội thất Poliform, Boffi",
    address: "Nguyễn Hữu Cảnh",
    district: "Quận Bình Thạnh",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600566753376-12c8ab7fb75b"),
    gallery: [img("photo-1600566753190-17f0baa2a6c3"), img("photo-1600566752355-35792bedcfea")],
    amenities: ["Sky bar riêng", "Hồ bơi sky", "Concierge 24/7"],
    highlights: ["Tầng cao nhất Việt Nam", "View 360°"],
    is_featured: true,
  },
  {
    slug: "villa-french-q7-phu-my-hung",
    title: "Villa Pháp cổ điển, Phú Mỹ Hưng, Q.7",
    subtitle: "600m² đất, phong cách Tân cổ điển",
    segment: "tren-10-ty",
    property_type: "villa",
    price: 42_000_000_000,
    area: 600.0,
    bedrooms: 5,
    bathrooms: 6,
    floors: 3,
    direction: "Nam",
    legal: "Sổ hồng",
    furniture: "Full nội thất Tân cổ điển",
    address: "Khu Mỹ Gia",
    district: "Quận 7",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1568605114967-8130f3a36994"),
    gallery: [img("photo-1613490493576-7fde63acd811"), img("photo-1600566753051-6057c5c34e6a")],
    amenities: ["Sân vườn Versailles", "Hồ bơi cổ điển", "Thư viện"],
    highlights: ["Phong cách Pháp nguyên bản", "Nhập khẩu nội thất Italy"],
  },
  {
    slug: "biet-thu-song-ca-tra-la-my-vinhomes-riverside",
    title: "Biệt thự song lập Vinhomes Riverside",
    subtitle: "Đảo riêng, 450m², bến du thuyền",
    segment: "tren-10-ty",
    property_type: "biet-thu",
    price: 28_000_000_000,
    area: 450.0,
    bedrooms: 5,
    bathrooms: 6,
    floors: 3,
    direction: "Đông Nam",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Long Biên",
    district: "Quận Long Biên",
    city: "Hà Nội",
    cover: img("photo-1613977257592-4871e5fcd7c4"),
    gallery: [img("photo-1613977257363-707ba9348227")],
    amenities: ["Đảo sinh thái", "Bến du thuyền", "Clubhouse 5 sao"],
    highlights: ["Mặt hồ trực diện", "Cộng đồng tinh hoa"],
  },
  {
    slug: "penthouse-art-deco-reverie-saigon-q1",
    title: "Penthouse Art Deco The Reverie Saigon, Q.1",
    subtitle: "Tầng thượng toà tháp đôi, 420m²",
    segment: "tren-10-ty",
    property_type: "penthouse",
    price: 68_000_000_000,
    area: 420.0,
    bedrooms: 4,
    bathrooms: 5,
    direction: "Tây Nam",
    legal: "Sổ hồng",
    furniture: "Nội thất Art Deco nguyên bản",
    address: "Nguyễn Huệ",
    district: "Quận 1",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600566753086-00f18fe6ba68"),
    gallery: [img("photo-1600566753376-12c8ab7fb75b"), img("photo-1600566752355-35792bedcfea")],
    amenities: ["6 sao concierge", "Butler riêng", "Rolls-Royce đưa đón"],
    highlights: ["Nằm giữa phố đi bộ", "View sông & Bitexco"],
  },
  {
    slug: "villa-compound-q2-hung-thinh",
    title: "Villa compound Q.2, phong cách Indochine",
    subtitle: "350m², sân vườn nhiệt đới",
    segment: "tren-10-ty",
    property_type: "villa",
    price: 22_000_000_000,
    area: 350.0,
    bedrooms: 5,
    bathrooms: 5,
    floors: 2,
    direction: "Đông",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Thảo Điền",
    district: "Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600607687939-ce8a6c25118c"),
    gallery: [img("photo-1600566753086-00f18fe6ba68")],
    amenities: ["Sân vườn nhiệt đới", "Hồ bơi", "Sauna"],
    highlights: ["Phong cách Indochine", "Compound 8 căn"],
  },
  {
    slug: "can-ho-sky-villa-serenity-q2",
    title: "Sky Villa Serenity Sky Villas, Q.2",
    subtitle: "Thông tầng trần 6m, 5PN",
    segment: "tren-10-ty",
    property_type: "penthouse",
    price: 18_500_000_000,
    area: 320.0,
    bedrooms: 5,
    bathrooms: 5,
    direction: "Đông",
    legal: "Sổ hồng",
    furniture: "Full nội thất",
    address: "Lương Định Của",
    district: "Quận 2",
    city: "TP. Hồ Chí Minh",
    cover: img("photo-1600566753376-12c8ab7fb75b"),
    gallery: [img("photo-1600566753190-17f0baa2a6c3")],
    amenities: ["Sky lounge", "Cinema", "Private gym"],
    highlights: ["Trần 6m thông tầng", "3 phòng ngủ master"],
  },
];

for (const p of properties) {
  const segId = sId[p.segment];
  if (!segId) {
    console.warn(`[seed] Unknown segment ${p.segment}`);
    continue;
  }
  const gallery = JSON.stringify(p.gallery || []);
  const amenities = JSON.stringify(p.amenities || []);
  const highlights = JSON.stringify(p.highlights || []);

  await sql`
    INSERT INTO properties (
      slug, title, subtitle, description, segment_id,
      property_type, status,
      price, area, bedrooms, bathrooms, floors,
      direction, legal, furniture,
      address, district, city,
      cover_image, gallery, amenities, highlights,
      is_featured, is_hero
    ) VALUES (
      ${p.slug}, ${p.title}, ${p.subtitle ?? null}, ${p.description ?? null}, ${segId},
      ${p.property_type}, ${p.status ?? "ban"},
      ${p.price}, ${p.area ?? null}, ${p.bedrooms ?? null}, ${p.bathrooms ?? null}, ${p.floors ?? null},
      ${p.direction ?? null}, ${p.legal ?? null}, ${p.furniture ?? null},
      ${p.address ?? null}, ${p.district ?? null}, ${p.city ?? null},
      ${p.cover}, ${gallery}::jsonb, ${amenities}::jsonb, ${highlights}::jsonb,
      ${p.is_featured ?? false}, ${p.is_hero ?? false}
    )
    ON CONFLICT (slug) DO UPDATE SET
      title = EXCLUDED.title,
      subtitle = EXCLUDED.subtitle,
      description = EXCLUDED.description,
      segment_id = EXCLUDED.segment_id,
      property_type = EXCLUDED.property_type,
      price = EXCLUDED.price,
      area = EXCLUDED.area,
      bedrooms = EXCLUDED.bedrooms,
      bathrooms = EXCLUDED.bathrooms,
      floors = EXCLUDED.floors,
      direction = EXCLUDED.direction,
      legal = EXCLUDED.legal,
      furniture = EXCLUDED.furniture,
      address = EXCLUDED.address,
      district = EXCLUDED.district,
      city = EXCLUDED.city,
      cover_image = EXCLUDED.cover_image,
      gallery = EXCLUDED.gallery,
      amenities = EXCLUDED.amenities,
      highlights = EXCLUDED.highlights,
      is_featured = EXCLUDED.is_featured,
      is_hero = EXCLUDED.is_hero,
      updated_at = NOW()
  `;
}
console.log(`[seed] Properties ready: ${properties.length}`);

// ---------------- Sample contact submissions ----------------
const submissions = [
  {
    name: "Trần Minh Quân",
    phone: "0909 123 456",
    email: "quan.tran@example.com",
    segment: "3 – 6 tỷ",
    message: "Mình đang tìm căn hộ 2PN khu Thủ Đức, ngân sách ~5 tỷ. Cuối tuần đi xem được không?",
    status: "new",
    minutesAgo: 12,
  },
  {
    name: "Nguyễn Thu Hà",
    phone: "0978 221 109",
    email: "ha.nguyen@example.com",
    segment: "Dưới 3 tỷ",
    message: "Có căn 1PN nào ở quận Bình Thạnh dưới 2.8 tỷ không ạ?",
    status: "new",
    minutesAgo: 48,
  },
  {
    name: "Phạm Quốc Anh",
    phone: "0933 817 000",
    email: null,
    segment: "Trên 10 tỷ",
    message: "Quan tâm penthouse Landmark 81 — cần thông tin hợp đồng và hỗ trợ pháp lý.",
    status: "contacted",
    note: "Đã gọi, khách hẹn xem trực tiếp tuần sau.",
    minutesAgo: 60 * 6,
  },
  {
    name: "Lê Hải Yến",
    phone: "0912 004 887",
    email: "yen.le@example.com",
    segment: "6 – 10 tỷ",
    message: "Cần biệt thự Thảo Điền, 3PN+ có sân vườn. Ngân sách linh hoạt 7-9 tỷ.",
    status: "contacted",
    note: "Đã gửi 3 căn qua Zalo.",
    minutesAgo: 60 * 20,
  },
  {
    name: "Đỗ Văn Dũng",
    phone: "0989 552 110",
    email: "dung.do@example.com",
    segment: "3 – 6 tỷ",
    message: "Đã mua xong, cảm ơn đội ngũ LOC!",
    status: "done",
    note: "Giao dịch thành công, căn Masteri M-One 4.2 tỷ.",
    minutesAgo: 60 * 24 * 3,
  },
  {
    name: "Võ Thị Lan",
    phone: "0934 226 998",
    email: null,
    segment: null,
    message: "Chỉ xem giá tham khảo",
    status: "trash",
    minutesAgo: 60 * 24 * 7,
  },
];

for (const s of submissions) {
  await sql`
    INSERT INTO contact_submissions (
      name, phone, email, segment, message, source, status, note, created_at, updated_at
    ) VALUES (
      ${s.name}, ${s.phone ?? null}, ${s.email ?? null}, ${s.segment ?? null},
      ${s.message ?? null}, 'contact-form', ${s.status}, ${s.note ?? null},
      NOW() - (${s.minutesAgo} * INTERVAL '1 minute'),
      NOW() - (${s.minutesAgo} * INTERVAL '1 minute')
    )
    ON CONFLICT DO NOTHING
  `;
}
console.log(`[seed] Submissions ready: ${submissions.length}`);

console.log("[seed] Done.");
